### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Ranger-X** [inossidabile/heimdallr-resource#1]
Hello! I created a new application with a scaffolded controller Users (and model User, of course). 
routes.rb:

``` ruby
resources :users
```

Gemfile:

``` ruby
...
gem 'heimdallr'
gem 'heimdallr-resource'
```

users_controller.rb:

``` ruby
class UsersController < ApplicationController
  include Heimdallr::Resource
  load_and_authorize_resource
...
```

But when I run this and go to http://localhost:3000/users/, I got an error:

``` ruby
Routing Error

uninitialized constant Heimdallr::Resource
Try running rake routes for more information on available routes.
```

and then, after page refreshing by F5:

``` ruby
NoMethodError in Users#index

Showing D:/Dev/Projects/zzz/app/views/users/index.html.erb where line #10 raised:

undefined method `each' for nil:NilClass
Extracted source (around line #10):

7:     <th></th>
8:   </tr>
9: 
10: <% @users.each do |user| %>
11:   <tr>
12:     <td><%= link_to 'Show', user %></td>
13:     <td><%= link_to 'Edit', edit_user_path(user) %></td>
```

P.S. Rails version 3.2.7, but also tried 3.2.5, 3.2.3 - same result.
Thanks in advance!

**Comment by adie** [comment]
First of all, try `load_and_authorize_resource :resource => :user`, if this solves your issue, then it was the same problem that I had (#2)

**Comment by Ranger-X** [comment]
This did not help. 
File lib/heimdallr/resource.rb was not required by Rails at boot-time. I created a file lib/heimdall-resource.rb in a Gem-directory with following content:

``` ruby
require 'heimdallr'
require "heimdallr/resource"
```

This solves above problem, but I got a new error :)

``` ruby
NoMethodError in UsersController#index

undefined method `security_context' for #<UsersController:0x6b9d480>
Rails.root: D:/Dev/Projects/zzz

Application Trace | Framework Trace | Full Trace
heimdallr-resource (1.0.3) lib/heimdallr/resource.rb:76:in `authorize'
heimdallr-resource (1.0.3) lib/heimdallr/resource.rb:198:in `block in authorize_resource'
activesupport (3.2.7) lib/active_support/callbacks.rb:429:in `_run__1028285054__process_action__294105470__callbacks'
activesupport (3.2.7) lib/active_support/callbacks.rb:405:in `__run_callback'
...
```

**Comment by adie** [comment]
Strange, it worked for me. But better not to add requires in the code, but do this in gemfile:

``` ruby
gem 'heimdallr-resource', :require => 'heimdallr/resource'
```

As for `security_context` error, I've simply added `def securty_context ; end` to the controller. But it seems to be a bug in the gem, because there is only a call to this method in the code, but I did not find where it is or should be defined.

**Comment by adie** [comment]
I've looked into tests, and found that `securty_context` method should be in `ApplicationController` and it should return current user.

**Comment by Ranger-X** [comment]
Big thanks! It's worked!
